fragment CompanyInfoParts on CompanyInfo {
  __typename
  name
  shortName
  founded
  years
  slogan
  taxCode
  director
  revenue
  staff
  website
  hotline
  hotlineTel
  email
  zalo
  facebook
  addresses {
    __typename
    key
    label
    address
    phone
    mapUrl
  }
}

fragment NewsParts on News {
  __typename
  title
  excerpt
  category
  date
  author
  readTime
  featured
  image
  body
}

fragment JobsParts on Jobs {
  __typename
  title
  department
  location
  type
  deadline
  fieldId
  description
  requirements
  benefits
  body
}

fragment FieldsParts on Fields {
  __typename
  slug
  name
  icon
  shortDesc
  description
  image
  stats {
    __typename
    label
    value
  }
  features
  services
}

fragment AwardsParts on Awards {
  __typename
  title
  issuer
  year
  image
  description
}

fragment PartnersParts on Partners {
  __typename
  name
  category
  logo
}

fragment TimelineParts on Timeline {
  __typename
  year
  title
  description
  milestone
}
