//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  companyInfo: CompanyInfo;
  companyInfoConnection: CompanyInfoConnection;
  news: News;
  newsConnection: NewsConnection;
  jobs: Jobs;
  jobsConnection: JobsConnection;
  fields: Fields;
  fieldsConnection: FieldsConnection;
  awards: Awards;
  awardsConnection: AwardsConnection;
  partners: Partners;
  partnersConnection: PartnersConnection;
  timeline: Timeline;
  timelineConnection: TimelineConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryCompanyInfoArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryCompanyInfoConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<CompanyInfoFilter>;
};


export type QueryNewsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNewsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<NewsFilter>;
};


export type QueryJobsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryJobsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<JobsFilter>;
};


export type QueryFieldsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryFieldsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<FieldsFilter>;
};


export type QueryAwardsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryAwardsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<AwardsFilter>;
};


export type QueryPartnersArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPartnersConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PartnersFilter>;
};


export type QueryTimelineArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryTimelineConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<TimelineFilter>;
};

export type DocumentFilter = {
  companyInfo?: InputMaybe<CompanyInfoFilter>;
  news?: InputMaybe<NewsFilter>;
  jobs?: InputMaybe<JobsFilter>;
  fields?: InputMaybe<FieldsFilter>;
  awards?: InputMaybe<AwardsFilter>;
  partners?: InputMaybe<PartnersFilter>;
  timeline?: InputMaybe<TimelineFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = CompanyInfo | News | Jobs | Fields | Awards | Partners | Timeline | Folder;

export type CompanyInfoAddresses = {
  __typename?: 'CompanyInfoAddresses';
  key?: Maybe<Scalars['String']['output']>;
  label?: Maybe<Scalars['String']['output']>;
  address?: Maybe<Scalars['String']['output']>;
  phone?: Maybe<Scalars['String']['output']>;
  mapUrl?: Maybe<Scalars['String']['output']>;
};

export type CompanyInfo = Node & Document & {
  __typename?: 'CompanyInfo';
  name: Scalars['String']['output'];
  shortName?: Maybe<Scalars['String']['output']>;
  founded?: Maybe<Scalars['Float']['output']>;
  years?: Maybe<Scalars['Float']['output']>;
  slogan?: Maybe<Scalars['String']['output']>;
  taxCode?: Maybe<Scalars['String']['output']>;
  director?: Maybe<Scalars['String']['output']>;
  revenue?: Maybe<Scalars['String']['output']>;
  staff?: Maybe<Scalars['String']['output']>;
  website?: Maybe<Scalars['String']['output']>;
  hotline?: Maybe<Scalars['String']['output']>;
  hotlineTel?: Maybe<Scalars['String']['output']>;
  email?: Maybe<Scalars['String']['output']>;
  zalo?: Maybe<Scalars['String']['output']>;
  facebook?: Maybe<Scalars['String']['output']>;
  addresses?: Maybe<Array<Maybe<CompanyInfoAddresses>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type NumberFilter = {
  lt?: InputMaybe<Scalars['Float']['input']>;
  lte?: InputMaybe<Scalars['Float']['input']>;
  gte?: InputMaybe<Scalars['Float']['input']>;
  gt?: InputMaybe<Scalars['Float']['input']>;
  eq?: InputMaybe<Scalars['Float']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['Float']['input']>>>;
};

export type CompanyInfoAddressesFilter = {
  key?: InputMaybe<StringFilter>;
  label?: InputMaybe<StringFilter>;
  address?: InputMaybe<StringFilter>;
  phone?: InputMaybe<StringFilter>;
  mapUrl?: InputMaybe<StringFilter>;
};

export type CompanyInfoFilter = {
  name?: InputMaybe<StringFilter>;
  shortName?: InputMaybe<StringFilter>;
  founded?: InputMaybe<NumberFilter>;
  years?: InputMaybe<NumberFilter>;
  slogan?: InputMaybe<StringFilter>;
  taxCode?: InputMaybe<StringFilter>;
  director?: InputMaybe<StringFilter>;
  revenue?: InputMaybe<StringFilter>;
  staff?: InputMaybe<StringFilter>;
  website?: InputMaybe<StringFilter>;
  hotline?: InputMaybe<StringFilter>;
  hotlineTel?: InputMaybe<StringFilter>;
  email?: InputMaybe<StringFilter>;
  zalo?: InputMaybe<StringFilter>;
  facebook?: InputMaybe<StringFilter>;
  addresses?: InputMaybe<CompanyInfoAddressesFilter>;
};

export type CompanyInfoConnectionEdges = {
  __typename?: 'CompanyInfoConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<CompanyInfo>;
};

export type CompanyInfoConnection = Connection & {
  __typename?: 'CompanyInfoConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<CompanyInfoConnectionEdges>>>;
};

export type News = Node & Document & {
  __typename?: 'News';
  title: Scalars['String']['output'];
  excerpt?: Maybe<Scalars['String']['output']>;
  category?: Maybe<Scalars['String']['output']>;
  date?: Maybe<Scalars['String']['output']>;
  author?: Maybe<Scalars['String']['output']>;
  readTime?: Maybe<Scalars['Float']['output']>;
  featured?: Maybe<Scalars['Boolean']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type DatetimeFilter = {
  after?: InputMaybe<Scalars['String']['input']>;
  before?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type BooleanFilter = {
  eq?: InputMaybe<Scalars['Boolean']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type RichTextFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type NewsFilter = {
  title?: InputMaybe<StringFilter>;
  excerpt?: InputMaybe<StringFilter>;
  category?: InputMaybe<StringFilter>;
  date?: InputMaybe<DatetimeFilter>;
  author?: InputMaybe<StringFilter>;
  readTime?: InputMaybe<NumberFilter>;
  featured?: InputMaybe<BooleanFilter>;
  image?: InputMaybe<ImageFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type NewsConnectionEdges = {
  __typename?: 'NewsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<News>;
};

export type NewsConnection = Connection & {
  __typename?: 'NewsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<NewsConnectionEdges>>>;
};

export type Jobs = Node & Document & {
  __typename?: 'Jobs';
  title: Scalars['String']['output'];
  department?: Maybe<Scalars['String']['output']>;
  location?: Maybe<Scalars['String']['output']>;
  type?: Maybe<Scalars['String']['output']>;
  deadline?: Maybe<Scalars['String']['output']>;
  fieldId?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  requirements?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  benefits?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type JobsFilter = {
  title?: InputMaybe<StringFilter>;
  department?: InputMaybe<StringFilter>;
  location?: InputMaybe<StringFilter>;
  type?: InputMaybe<StringFilter>;
  deadline?: InputMaybe<StringFilter>;
  fieldId?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  requirements?: InputMaybe<StringFilter>;
  benefits?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type JobsConnectionEdges = {
  __typename?: 'JobsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Jobs>;
};

export type JobsConnection = Connection & {
  __typename?: 'JobsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<JobsConnectionEdges>>>;
};

export type FieldsStats = {
  __typename?: 'FieldsStats';
  label?: Maybe<Scalars['String']['output']>;
  value?: Maybe<Scalars['String']['output']>;
};

export type Fields = Node & Document & {
  __typename?: 'Fields';
  slug: Scalars['String']['output'];
  name: Scalars['String']['output'];
  icon?: Maybe<Scalars['String']['output']>;
  shortDesc?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  stats?: Maybe<Array<Maybe<FieldsStats>>>;
  features?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  services?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type FieldsStatsFilter = {
  label?: InputMaybe<StringFilter>;
  value?: InputMaybe<StringFilter>;
};

export type FieldsFilter = {
  slug?: InputMaybe<StringFilter>;
  name?: InputMaybe<StringFilter>;
  icon?: InputMaybe<StringFilter>;
  shortDesc?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  stats?: InputMaybe<FieldsStatsFilter>;
  features?: InputMaybe<StringFilter>;
  services?: InputMaybe<StringFilter>;
};

export type FieldsConnectionEdges = {
  __typename?: 'FieldsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Fields>;
};

export type FieldsConnection = Connection & {
  __typename?: 'FieldsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<FieldsConnectionEdges>>>;
};

export type Awards = Node & Document & {
  __typename?: 'Awards';
  title: Scalars['String']['output'];
  issuer?: Maybe<Scalars['String']['output']>;
  year?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type AwardsFilter = {
  title?: InputMaybe<StringFilter>;
  issuer?: InputMaybe<StringFilter>;
  year?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  description?: InputMaybe<StringFilter>;
};

export type AwardsConnectionEdges = {
  __typename?: 'AwardsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Awards>;
};

export type AwardsConnection = Connection & {
  __typename?: 'AwardsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<AwardsConnectionEdges>>>;
};

export type Partners = Node & Document & {
  __typename?: 'Partners';
  name: Scalars['String']['output'];
  category?: Maybe<Scalars['String']['output']>;
  logo?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type PartnersFilter = {
  name?: InputMaybe<StringFilter>;
  category?: InputMaybe<StringFilter>;
  logo?: InputMaybe<ImageFilter>;
};

export type PartnersConnectionEdges = {
  __typename?: 'PartnersConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Partners>;
};

export type PartnersConnection = Connection & {
  __typename?: 'PartnersConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PartnersConnectionEdges>>>;
};

export type Timeline = Node & Document & {
  __typename?: 'Timeline';
  year: Scalars['String']['output'];
  title: Scalars['String']['output'];
  description?: Maybe<Scalars['String']['output']>;
  milestone?: Maybe<Scalars['Boolean']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type TimelineFilter = {
  year?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  milestone?: InputMaybe<BooleanFilter>;
};

export type TimelineConnectionEdges = {
  __typename?: 'TimelineConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Timeline>;
};

export type TimelineConnection = Connection & {
  __typename?: 'TimelineConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<TimelineConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateCompanyInfo: CompanyInfo;
  createCompanyInfo: CompanyInfo;
  updateNews: News;
  createNews: News;
  updateJobs: Jobs;
  createJobs: Jobs;
  updateFields: Fields;
  createFields: Fields;
  updateAwards: Awards;
  createAwards: Awards;
  updatePartners: Partners;
  createPartners: Partners;
  updateTimeline: Timeline;
  createTimeline: Timeline;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateCompanyInfoArgs = {
  relativePath: Scalars['String']['input'];
  params: CompanyInfoMutation;
};


export type MutationCreateCompanyInfoArgs = {
  relativePath: Scalars['String']['input'];
  params: CompanyInfoMutation;
};


export type MutationUpdateNewsArgs = {
  relativePath: Scalars['String']['input'];
  params: NewsMutation;
};


export type MutationCreateNewsArgs = {
  relativePath: Scalars['String']['input'];
  params: NewsMutation;
};


export type MutationUpdateJobsArgs = {
  relativePath: Scalars['String']['input'];
  params: JobsMutation;
};


export type MutationCreateJobsArgs = {
  relativePath: Scalars['String']['input'];
  params: JobsMutation;
};


export type MutationUpdateFieldsArgs = {
  relativePath: Scalars['String']['input'];
  params: FieldsMutation;
};


export type MutationCreateFieldsArgs = {
  relativePath: Scalars['String']['input'];
  params: FieldsMutation;
};


export type MutationUpdateAwardsArgs = {
  relativePath: Scalars['String']['input'];
  params: AwardsMutation;
};


export type MutationCreateAwardsArgs = {
  relativePath: Scalars['String']['input'];
  params: AwardsMutation;
};


export type MutationUpdatePartnersArgs = {
  relativePath: Scalars['String']['input'];
  params: PartnersMutation;
};


export type MutationCreatePartnersArgs = {
  relativePath: Scalars['String']['input'];
  params: PartnersMutation;
};


export type MutationUpdateTimelineArgs = {
  relativePath: Scalars['String']['input'];
  params: TimelineMutation;
};


export type MutationCreateTimelineArgs = {
  relativePath: Scalars['String']['input'];
  params: TimelineMutation;
};

export type DocumentUpdateMutation = {
  companyInfo?: InputMaybe<CompanyInfoMutation>;
  news?: InputMaybe<NewsMutation>;
  jobs?: InputMaybe<JobsMutation>;
  fields?: InputMaybe<FieldsMutation>;
  awards?: InputMaybe<AwardsMutation>;
  partners?: InputMaybe<PartnersMutation>;
  timeline?: InputMaybe<TimelineMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  companyInfo?: InputMaybe<CompanyInfoMutation>;
  news?: InputMaybe<NewsMutation>;
  jobs?: InputMaybe<JobsMutation>;
  fields?: InputMaybe<FieldsMutation>;
  awards?: InputMaybe<AwardsMutation>;
  partners?: InputMaybe<PartnersMutation>;
  timeline?: InputMaybe<TimelineMutation>;
};

export type CompanyInfoAddressesMutation = {
  key?: InputMaybe<Scalars['String']['input']>;
  label?: InputMaybe<Scalars['String']['input']>;
  address?: InputMaybe<Scalars['String']['input']>;
  phone?: InputMaybe<Scalars['String']['input']>;
  mapUrl?: InputMaybe<Scalars['String']['input']>;
};

export type CompanyInfoMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  shortName?: InputMaybe<Scalars['String']['input']>;
  founded?: InputMaybe<Scalars['Float']['input']>;
  years?: InputMaybe<Scalars['Float']['input']>;
  slogan?: InputMaybe<Scalars['String']['input']>;
  taxCode?: InputMaybe<Scalars['String']['input']>;
  director?: InputMaybe<Scalars['String']['input']>;
  revenue?: InputMaybe<Scalars['String']['input']>;
  staff?: InputMaybe<Scalars['String']['input']>;
  website?: InputMaybe<Scalars['String']['input']>;
  hotline?: InputMaybe<Scalars['String']['input']>;
  hotlineTel?: InputMaybe<Scalars['String']['input']>;
  email?: InputMaybe<Scalars['String']['input']>;
  zalo?: InputMaybe<Scalars['String']['input']>;
  facebook?: InputMaybe<Scalars['String']['input']>;
  addresses?: InputMaybe<Array<InputMaybe<CompanyInfoAddressesMutation>>>;
};

export type NewsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  excerpt?: InputMaybe<Scalars['String']['input']>;
  category?: InputMaybe<Scalars['String']['input']>;
  date?: InputMaybe<Scalars['String']['input']>;
  author?: InputMaybe<Scalars['String']['input']>;
  readTime?: InputMaybe<Scalars['Float']['input']>;
  featured?: InputMaybe<Scalars['Boolean']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type JobsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  department?: InputMaybe<Scalars['String']['input']>;
  location?: InputMaybe<Scalars['String']['input']>;
  type?: InputMaybe<Scalars['String']['input']>;
  deadline?: InputMaybe<Scalars['String']['input']>;
  fieldId?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  requirements?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  benefits?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type FieldsStatsMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  value?: InputMaybe<Scalars['String']['input']>;
};

export type FieldsMutation = {
  slug?: InputMaybe<Scalars['String']['input']>;
  name?: InputMaybe<Scalars['String']['input']>;
  icon?: InputMaybe<Scalars['String']['input']>;
  shortDesc?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  stats?: InputMaybe<Array<InputMaybe<FieldsStatsMutation>>>;
  features?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  services?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type AwardsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  issuer?: InputMaybe<Scalars['String']['input']>;
  year?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
};

export type PartnersMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  category?: InputMaybe<Scalars['String']['input']>;
  logo?: InputMaybe<Scalars['String']['input']>;
};

export type TimelineMutation = {
  year?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  milestone?: InputMaybe<Scalars['Boolean']['input']>;
};

export type CompanyInfoPartsFragment = { __typename: 'CompanyInfo', name: string, shortName?: string | null, founded?: number | null, years?: number | null, slogan?: string | null, taxCode?: string | null, director?: string | null, revenue?: string | null, staff?: string | null, website?: string | null, hotline?: string | null, hotlineTel?: string | null, email?: string | null, zalo?: string | null, facebook?: string | null, addresses?: Array<{ __typename: 'CompanyInfoAddresses', key?: string | null, label?: string | null, address?: string | null, phone?: string | null, mapUrl?: string | null } | null> | null };

export type NewsPartsFragment = { __typename: 'News', title: string, excerpt?: string | null, category?: string | null, date?: string | null, author?: string | null, readTime?: number | null, featured?: boolean | null, image?: string | null, body?: any | null };

export type JobsPartsFragment = { __typename: 'Jobs', title: string, department?: string | null, location?: string | null, type?: string | null, deadline?: string | null, fieldId?: string | null, description?: string | null, requirements?: Array<string | null> | null, benefits?: Array<string | null> | null, body?: any | null };

export type FieldsPartsFragment = { __typename: 'Fields', slug: string, name: string, icon?: string | null, shortDesc?: string | null, description?: string | null, image?: string | null, features?: Array<string | null> | null, services?: Array<string | null> | null, stats?: Array<{ __typename: 'FieldsStats', label?: string | null, value?: string | null } | null> | null };

export type AwardsPartsFragment = { __typename: 'Awards', title: string, issuer?: string | null, year?: string | null, image?: string | null, description?: string | null };

export type PartnersPartsFragment = { __typename: 'Partners', name: string, category?: string | null, logo?: string | null };

export type TimelinePartsFragment = { __typename: 'Timeline', year: string, title: string, description?: string | null, milestone?: boolean | null };

export type CompanyInfoQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type CompanyInfoQuery = { __typename?: 'Query', companyInfo: { __typename: 'CompanyInfo', id: string, name: string, shortName?: string | null, founded?: number | null, years?: number | null, slogan?: string | null, taxCode?: string | null, director?: string | null, revenue?: string | null, staff?: string | null, website?: string | null, hotline?: string | null, hotlineTel?: string | null, email?: string | null, zalo?: string | null, facebook?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, addresses?: Array<{ __typename: 'CompanyInfoAddresses', key?: string | null, label?: string | null, address?: string | null, phone?: string | null, mapUrl?: string | null } | null> | null } };

export type CompanyInfoConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<CompanyInfoFilter>;
}>;


export type CompanyInfoConnectionQuery = { __typename?: 'Query', companyInfoConnection: { __typename?: 'CompanyInfoConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'CompanyInfoConnectionEdges', cursor: string, node?: { __typename: 'CompanyInfo', id: string, name: string, shortName?: string | null, founded?: number | null, years?: number | null, slogan?: string | null, taxCode?: string | null, director?: string | null, revenue?: string | null, staff?: string | null, website?: string | null, hotline?: string | null, hotlineTel?: string | null, email?: string | null, zalo?: string | null, facebook?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, addresses?: Array<{ __typename: 'CompanyInfoAddresses', key?: string | null, label?: string | null, address?: string | null, phone?: string | null, mapUrl?: string | null } | null> | null } | null } | null> | null } };

export type NewsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type NewsQuery = { __typename?: 'Query', news: { __typename: 'News', id: string, title: string, excerpt?: string | null, category?: string | null, date?: string | null, author?: string | null, readTime?: number | null, featured?: boolean | null, image?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type NewsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<NewsFilter>;
}>;


export type NewsConnectionQuery = { __typename?: 'Query', newsConnection: { __typename?: 'NewsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'NewsConnectionEdges', cursor: string, node?: { __typename: 'News', id: string, title: string, excerpt?: string | null, category?: string | null, date?: string | null, author?: string | null, readTime?: number | null, featured?: boolean | null, image?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type JobsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type JobsQuery = { __typename?: 'Query', jobs: { __typename: 'Jobs', id: string, title: string, department?: string | null, location?: string | null, type?: string | null, deadline?: string | null, fieldId?: string | null, description?: string | null, requirements?: Array<string | null> | null, benefits?: Array<string | null> | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type JobsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<JobsFilter>;
}>;


export type JobsConnectionQuery = { __typename?: 'Query', jobsConnection: { __typename?: 'JobsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'JobsConnectionEdges', cursor: string, node?: { __typename: 'Jobs', id: string, title: string, department?: string | null, location?: string | null, type?: string | null, deadline?: string | null, fieldId?: string | null, description?: string | null, requirements?: Array<string | null> | null, benefits?: Array<string | null> | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type FieldsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type FieldsQuery = { __typename?: 'Query', fields: { __typename: 'Fields', id: string, slug: string, name: string, icon?: string | null, shortDesc?: string | null, description?: string | null, image?: string | null, features?: Array<string | null> | null, services?: Array<string | null> | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, stats?: Array<{ __typename: 'FieldsStats', label?: string | null, value?: string | null } | null> | null } };

export type FieldsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<FieldsFilter>;
}>;


export type FieldsConnectionQuery = { __typename?: 'Query', fieldsConnection: { __typename?: 'FieldsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'FieldsConnectionEdges', cursor: string, node?: { __typename: 'Fields', id: string, slug: string, name: string, icon?: string | null, shortDesc?: string | null, description?: string | null, image?: string | null, features?: Array<string | null> | null, services?: Array<string | null> | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, stats?: Array<{ __typename: 'FieldsStats', label?: string | null, value?: string | null } | null> | null } | null } | null> | null } };

export type AwardsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type AwardsQuery = { __typename?: 'Query', awards: { __typename: 'Awards', id: string, title: string, issuer?: string | null, year?: string | null, image?: string | null, description?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type AwardsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<AwardsFilter>;
}>;


export type AwardsConnectionQuery = { __typename?: 'Query', awardsConnection: { __typename?: 'AwardsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'AwardsConnectionEdges', cursor: string, node?: { __typename: 'Awards', id: string, title: string, issuer?: string | null, year?: string | null, image?: string | null, description?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type PartnersQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type PartnersQuery = { __typename?: 'Query', partners: { __typename: 'Partners', id: string, name: string, category?: string | null, logo?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type PartnersConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PartnersFilter>;
}>;


export type PartnersConnectionQuery = { __typename?: 'Query', partnersConnection: { __typename?: 'PartnersConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'PartnersConnectionEdges', cursor: string, node?: { __typename: 'Partners', id: string, name: string, category?: string | null, logo?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type TimelineQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type TimelineQuery = { __typename?: 'Query', timeline: { __typename: 'Timeline', id: string, year: string, title: string, description?: string | null, milestone?: boolean | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type TimelineConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<TimelineFilter>;
}>;


export type TimelineConnectionQuery = { __typename?: 'Query', timelineConnection: { __typename?: 'TimelineConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'TimelineConnectionEdges', cursor: string, node?: { __typename: 'Timeline', id: string, year: string, title: string, description?: string | null, milestone?: boolean | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export const CompanyInfoPartsFragmentDoc = gql`
    fragment CompanyInfoParts on CompanyInfo {
  __typename
  name
  shortName
  founded
  years
  slogan
  taxCode
  director
  revenue
  staff
  website
  hotline
  hotlineTel
  email
  zalo
  facebook
  addresses {
    __typename
    key
    label
    address
    phone
    mapUrl
  }
}
    `;
export const NewsPartsFragmentDoc = gql`
    fragment NewsParts on News {
  __typename
  title
  excerpt
  category
  date
  author
  readTime
  featured
  image
  body
}
    `;
export const JobsPartsFragmentDoc = gql`
    fragment JobsParts on Jobs {
  __typename
  title
  department
  location
  type
  deadline
  fieldId
  description
  requirements
  benefits
  body
}
    `;
export const FieldsPartsFragmentDoc = gql`
    fragment FieldsParts on Fields {
  __typename
  slug
  name
  icon
  shortDesc
  description
  image
  stats {
    __typename
    label
    value
  }
  features
  services
}
    `;
export const AwardsPartsFragmentDoc = gql`
    fragment AwardsParts on Awards {
  __typename
  title
  issuer
  year
  image
  description
}
    `;
export const PartnersPartsFragmentDoc = gql`
    fragment PartnersParts on Partners {
  __typename
  name
  category
  logo
}
    `;
export const TimelinePartsFragmentDoc = gql`
    fragment TimelineParts on Timeline {
  __typename
  year
  title
  description
  milestone
}
    `;
export const CompanyInfoDocument = gql`
    query companyInfo($relativePath: String!) {
  companyInfo(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...CompanyInfoParts
  }
}
    ${CompanyInfoPartsFragmentDoc}`;
export const CompanyInfoConnectionDocument = gql`
    query companyInfoConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: CompanyInfoFilter) {
  companyInfoConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...CompanyInfoParts
      }
    }
  }
}
    ${CompanyInfoPartsFragmentDoc}`;
export const NewsDocument = gql`
    query news($relativePath: String!) {
  news(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...NewsParts
  }
}
    ${NewsPartsFragmentDoc}`;
export const NewsConnectionDocument = gql`
    query newsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: NewsFilter) {
  newsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...NewsParts
      }
    }
  }
}
    ${NewsPartsFragmentDoc}`;
export const JobsDocument = gql`
    query jobs($relativePath: String!) {
  jobs(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...JobsParts
  }
}
    ${JobsPartsFragmentDoc}`;
export const JobsConnectionDocument = gql`
    query jobsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: JobsFilter) {
  jobsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...JobsParts
      }
    }
  }
}
    ${JobsPartsFragmentDoc}`;
export const FieldsDocument = gql`
    query fields($relativePath: String!) {
  fields(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...FieldsParts
  }
}
    ${FieldsPartsFragmentDoc}`;
export const FieldsConnectionDocument = gql`
    query fieldsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: FieldsFilter) {
  fieldsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...FieldsParts
      }
    }
  }
}
    ${FieldsPartsFragmentDoc}`;
export const AwardsDocument = gql`
    query awards($relativePath: String!) {
  awards(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...AwardsParts
  }
}
    ${AwardsPartsFragmentDoc}`;
export const AwardsConnectionDocument = gql`
    query awardsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: AwardsFilter) {
  awardsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...AwardsParts
      }
    }
  }
}
    ${AwardsPartsFragmentDoc}`;
export const PartnersDocument = gql`
    query partners($relativePath: String!) {
  partners(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PartnersParts
  }
}
    ${PartnersPartsFragmentDoc}`;
export const PartnersConnectionDocument = gql`
    query partnersConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PartnersFilter) {
  partnersConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PartnersParts
      }
    }
  }
}
    ${PartnersPartsFragmentDoc}`;
export const TimelineDocument = gql`
    query timeline($relativePath: String!) {
  timeline(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...TimelineParts
  }
}
    ${TimelinePartsFragmentDoc}`;
export const TimelineConnectionDocument = gql`
    query timelineConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: TimelineFilter) {
  timelineConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...TimelineParts
      }
    }
  }
}
    ${TimelinePartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      companyInfo(variables: CompanyInfoQueryVariables, options?: C): Promise<{data: CompanyInfoQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: CompanyInfoQueryVariables, query: string}> {
        return requester<{data: CompanyInfoQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: CompanyInfoQueryVariables, query: string}, CompanyInfoQueryVariables>(CompanyInfoDocument, variables, options);
      },
    companyInfoConnection(variables?: CompanyInfoConnectionQueryVariables, options?: C): Promise<{data: CompanyInfoConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: CompanyInfoConnectionQueryVariables, query: string}> {
        return requester<{data: CompanyInfoConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: CompanyInfoConnectionQueryVariables, query: string}, CompanyInfoConnectionQueryVariables>(CompanyInfoConnectionDocument, variables, options);
      },
    news(variables: NewsQueryVariables, options?: C): Promise<{data: NewsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: NewsQueryVariables, query: string}> {
        return requester<{data: NewsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: NewsQueryVariables, query: string}, NewsQueryVariables>(NewsDocument, variables, options);
      },
    newsConnection(variables?: NewsConnectionQueryVariables, options?: C): Promise<{data: NewsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: NewsConnectionQueryVariables, query: string}> {
        return requester<{data: NewsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: NewsConnectionQueryVariables, query: string}, NewsConnectionQueryVariables>(NewsConnectionDocument, variables, options);
      },
    jobs(variables: JobsQueryVariables, options?: C): Promise<{data: JobsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: JobsQueryVariables, query: string}> {
        return requester<{data: JobsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: JobsQueryVariables, query: string}, JobsQueryVariables>(JobsDocument, variables, options);
      },
    jobsConnection(variables?: JobsConnectionQueryVariables, options?: C): Promise<{data: JobsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: JobsConnectionQueryVariables, query: string}> {
        return requester<{data: JobsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: JobsConnectionQueryVariables, query: string}, JobsConnectionQueryVariables>(JobsConnectionDocument, variables, options);
      },
    fields(variables: FieldsQueryVariables, options?: C): Promise<{data: FieldsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FieldsQueryVariables, query: string}> {
        return requester<{data: FieldsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FieldsQueryVariables, query: string}, FieldsQueryVariables>(FieldsDocument, variables, options);
      },
    fieldsConnection(variables?: FieldsConnectionQueryVariables, options?: C): Promise<{data: FieldsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FieldsConnectionQueryVariables, query: string}> {
        return requester<{data: FieldsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FieldsConnectionQueryVariables, query: string}, FieldsConnectionQueryVariables>(FieldsConnectionDocument, variables, options);
      },
    awards(variables: AwardsQueryVariables, options?: C): Promise<{data: AwardsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AwardsQueryVariables, query: string}> {
        return requester<{data: AwardsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AwardsQueryVariables, query: string}, AwardsQueryVariables>(AwardsDocument, variables, options);
      },
    awardsConnection(variables?: AwardsConnectionQueryVariables, options?: C): Promise<{data: AwardsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AwardsConnectionQueryVariables, query: string}> {
        return requester<{data: AwardsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AwardsConnectionQueryVariables, query: string}, AwardsConnectionQueryVariables>(AwardsConnectionDocument, variables, options);
      },
    partners(variables: PartnersQueryVariables, options?: C): Promise<{data: PartnersQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PartnersQueryVariables, query: string}> {
        return requester<{data: PartnersQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PartnersQueryVariables, query: string}, PartnersQueryVariables>(PartnersDocument, variables, options);
      },
    partnersConnection(variables?: PartnersConnectionQueryVariables, options?: C): Promise<{data: PartnersConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PartnersConnectionQueryVariables, query: string}> {
        return requester<{data: PartnersConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PartnersConnectionQueryVariables, query: string}, PartnersConnectionQueryVariables>(PartnersConnectionDocument, variables, options);
      },
    timeline(variables: TimelineQueryVariables, options?: C): Promise<{data: TimelineQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TimelineQueryVariables, query: string}> {
        return requester<{data: TimelineQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TimelineQueryVariables, query: string}, TimelineQueryVariables>(TimelineDocument, variables, options);
      },
    timelineConnection(variables?: TimelineConnectionQueryVariables, options?: C): Promise<{data: TimelineConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TimelineConnectionQueryVariables, query: string}> {
        return requester<{data: TimelineConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TimelineConnectionQueryVariables, query: string}, TimelineConnectionQueryVariables>(TimelineConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  